spring.application.name=fittrack

spring.datasource.url=jdbc:postgresql://localhost:5433/fittrack
spring.datasource.username=fittrack
spring.datasource.password=fittrack
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000